# Generated by Django 2.2.4 on 2023-12-20 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bucket',
            new_name='Purchase',
        ),
    ]
