# Generated by Django 2.2.4 on 2023-12-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_app', '0005_user_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_title',
            field=models.CharField(default='aa', max_length=45),
            preserve_default=False,
        ),
    ]
