# Generated by Django 2.2.4 on 2023-12-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_app', '0008_auto_20231225_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
    ]
