# Generated by Django 2.2.4 on 2023-12-25 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f_app', '0011_auto_20231225_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product_title',
        ),
        migrations.AddField(
            model_name='purchase',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f_app.Product'),
        ),
    ]
