# Generated by Django 2.2.4 on 2023-12-25 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f_app', '0012_auto_20231225_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f_app.Product'),
        ),
    ]
