# Generated by Django 2.2.4 on 2023-12-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_app', '0013_auto_20231225_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='product_id',
        ),
        migrations.AddField(
            model_name='purchase',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='product_title',
            field=models.CharField(default=10, max_length=45),
            preserve_default=False,
        ),
    ]
